#!/usr/bin/env bash
# ============================================================
# setup-linux.sh
# NerdAlert setup for Ubuntu/Linux (Sherman's PC)
#
# Run this once on the Linux machine:
#   bash setup-linux.sh
#
# What it does:
#   1. Checks Node.js version (18+ required)
#   2. npm install
#   3. Generates a server auth token
#   4. Creates .env with all required values
#   5. Prompts for Telegram bot token + chat ID
#   6. Prompts for model provider (Anthropic or OpenRouter)
#   7. Installs systemd service so the bot starts on boot
#   8. Builds TypeScript
#   9. Starts the service
# ============================================================

set -e

NERDALERT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_NAME="nerdalert@${USER}"
SERVICE_FILE="nerdalert@.service"
SYSTEMD_DIR="/etc/systemd/system"

echo ""
echo "  ███╗   ██╗███████╗██████╗ ██████╗  █████╗ ██╗     ███████╗██████╗ ████████╗"
echo "  ████╗  ██║██╔════╝██╔══██╗██╔══██╗██╔══██╗██║     ██╔════╝██╔══██╗╚══██╔══╝"
echo "  ██╔██╗ ██║█████╗  ██████╔╝██║  ██║███████║██║     █████╗  ██████╔╝   ██║   "
echo "  ██║╚██╗██║██╔══╝  ██╔══██╗██║  ██║██╔══██║██║     ██╔══╝  ██╔══██╗   ██║   "
echo "  ██║ ╚████║███████╗██║  ██║██████╔╝██║  ██║███████╗███████╗██║  ██║   ██║   "
echo "  ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝   ╚═╝   "
echo ""
echo "  Linux Setup // Sherman's PC"
echo ""

# ── 1. Node version check ─────────────────────────────────────
echo "→ Checking Node.js..."
if ! command -v node &>/dev/null; then
  echo "  ✗ Node.js not found. Install Node 18+ first:"
  echo "    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -"
  echo "    sudo apt-get install -y nodejs"
  exit 1
fi

NODE_MAJOR=$(node -e "process.stdout.write(String(process.version.split('.')[0].slice(1)))")
if [ "$NODE_MAJOR" -lt 18 ]; then
  echo "  ✗ Node.js 18+ required (found v$(node -v))"
  echo "    Update with: sudo npm install -g n && sudo n 20"
  exit 1
fi
echo "  ✓ Node.js $(node -v)"

# ── 2. npm install ────────────────────────────────────────────
echo ""
echo "→ Installing dependencies..."
cd "$NERDALERT_DIR"
npm install --silent
echo "  ✓ Dependencies installed"

# ── 3. Check for existing .env ────────────────────────────────
echo ""
if [ -f ".env" ]; then
  echo "→ Existing .env found — skipping token generation"
  echo "  (Delete .env and re-run setup if you want to reset)"
else
  echo "→ Creating .env..."

  # Generate server auth token
  SERVER_TOKEN=$(node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))")

  cat > .env << EOF
# NerdAlert configuration
# Generated by setup-linux.sh on $(date)

# Server auth token — keep this private
SERVER_AUTH_TOKEN=${SERVER_TOKEN}

# Model — uncomment one:
# MODEL=anthropic/claude-sonnet-4-6
MODEL=nvidia/llama-3.1-nemotron-70b-instruct:free

# API keys — fill in what you're using:
OPENROUTER_API_KEY=
ANTHROPIC_API_KEY=

# Telegram bot — required for alerts and two-way chat
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=

# OpenClaw gateway (for SOC tools) — set if running OpenClaw
OPENCLAW_URL=
OPENCLAW_TOKEN=

# Gmail (optional)
# GMAIL_CONFIG_PATH=~/.nerdalert/secrets/email-gmail.json
# GOOGLE_CALENDAR_SECRET_PATH=~/.nerdalert/secrets/google-calendar.json
EOF

  echo "  ✓ .env created"
fi

# ── 4. Telegram setup ─────────────────────────────────────────
echo ""
echo "→ Telegram setup"
echo ""

# Check if already set
EXISTING_TOKEN=$(grep "^TELEGRAM_BOT_TOKEN=" .env | cut -d= -f2)
if [ -z "$EXISTING_TOKEN" ]; then
  echo "  You need a Telegram bot token from @BotFather."
  echo "  1. Open Telegram and message @BotFather"
  echo "  2. Send /newbot and follow the prompts"
  echo "  3. Copy the token it gives you"
  echo ""
  read -rp "  Paste your bot token: " BOT_TOKEN
  sed -i "s|^TELEGRAM_BOT_TOKEN=.*|TELEGRAM_BOT_TOKEN=${BOT_TOKEN}|" .env
  echo "  ✓ Bot token saved"
else
  echo "  ✓ Bot token already set"
fi

echo ""
EXISTING_CHAT=$(grep "^TELEGRAM_CHAT_ID=" .env | cut -d= -f2)
if [ -z "$EXISTING_CHAT" ]; then
  echo "  To get your chat ID:"
  echo "  1. Start a conversation with your bot in Telegram"
  echo "  2. Send any message to it"
  echo "  3. Visit: https://api.telegram.org/bot<YOUR_TOKEN>/getUpdates"
  echo "  4. Find 'chat':{'id': XXXXXXX} in the response"
  echo ""
  read -rp "  Paste your chat ID: " CHAT_ID
  sed -i "s|^TELEGRAM_CHAT_ID=.*|TELEGRAM_CHAT_ID=${CHAT_ID}|" .env
  echo "  ✓ Chat ID saved"
else
  echo "  ✓ Chat ID already set"
fi

# ── 5. Model / API key setup ──────────────────────────────────
echo ""
echo "→ Model setup"
echo ""
echo "  Which model do you want to use?"
echo "  1) Nemotron 70B (free, OpenRouter) — recommended for this machine"
echo "  2) Claude Sonnet 4.6 (Anthropic API key required)"
echo ""
read -rp "  Choice [1/2]: " MODEL_CHOICE

if [ "$MODEL_CHOICE" = "2" ]; then
  read -rp "  Paste your Anthropic API key: " ANT_KEY
  sed -i "s|^MODEL=.*|MODEL=anthropic/claude-sonnet-4-6|" .env
  sed -i "s|^ANTHROPIC_API_KEY=.*|ANTHROPIC_API_KEY=${ANT_KEY}|" .env
  echo "  ✓ Claude configured"
else
  read -rp "  Paste your OpenRouter API key (free at openrouter.ai): " OR_KEY
  sed -i "s|^MODEL=.*|MODEL=nvidia/llama-3.1-nemotron-70b-instruct:free|" .env
  sed -i "s|^OPENROUTER_API_KEY=.*|OPENROUTER_API_KEY=${OR_KEY}|" .env
  echo "  ✓ Nemotron configured"
fi

# ── 6. Build TypeScript ───────────────────────────────────────
echo ""
echo "→ Building TypeScript..."
npm run build
echo "  ✓ Build complete"

# ── 7. Shell alias (bashrc) ───────────────────────────────────
echo ""
echo "→ Adding shell aliases to ~/.bashrc..."

BASHRC="$HOME/.bashrc"
if ! grep -q "# NerdAlert aliases" "$BASHRC" 2>/dev/null; then
  cat >> "$BASHRC" << EOF

# NerdAlert aliases
alias nerd-start="cd ${NERDALERT_DIR} && npm run build && node dist/server/index.js"
alias nerd-logs="sudo journalctl -u ${SERVICE_NAME} -f"
alias nerd-restart="sudo systemctl restart ${SERVICE_NAME}"
alias nerd-status="sudo systemctl status ${SERVICE_NAME}"
EOF
  echo "  ✓ Aliases added (run 'source ~/.bashrc' to activate)"
else
  echo "  ✓ Aliases already present"
fi

# ── 8. systemd service ────────────────────────────────────────
echo ""
echo "→ Installing systemd service..."

if [ -f "$SERVICE_FILE" ]; then
  sudo cp "$SERVICE_FILE" "$SYSTEMD_DIR/"
  sudo systemctl daemon-reload
  sudo systemctl enable "$SERVICE_NAME"
  sudo systemctl start "$SERVICE_NAME"
  echo "  ✓ Service installed and started"
  echo "  ✓ Will auto-start on boot"
else
  echo "  ⚠ nerdalert@.service not found — skipping systemd install"
  echo "  Start manually with: nerd-start"
fi

# ── Done ──────────────────────────────────────────────────────
echo ""
echo "  ══════════════════════════════════════════"
echo "  Setup complete."
echo ""
echo "  Check status:  nerd-status"
echo "  View logs:     nerd-logs"
echo "  Restart:       nerd-restart"
echo ""
echo "  Test Telegram by sending a message to your bot."
echo "  ══════════════════════════════════════════"
echo ""
